TRUNCATE TABLE
  experts_languages,
  experts,
  users,
  specialties,
  languages
RESTART IDENTITY CASCADE;

INSERT INTO
  users (id, email, password_hash, full_name, date_of_birth, gender, email_verified)
VALUES
  ('cuid123456789abcdef0001', 'alice@example.com', '$2b$12$abc123fakebcryptpasswordhash0000000000000000000', 'alice smith', '1980-05-10', 'F', true)
;

INSERT INTO
  specialties (name)
VALUES
  ('acupuncture'),
  ('cardiology'),
  ('dentistry'),
  ('dermatology'),
  ('dietary counseling'),
  ('family medicine'),
  ('genetic counseling'),
  ('massage therapy'),
  ('midwifery'),
  ('occupational therapy'),
  ('ophthalmology'),
  ('orthopedic surgery'),
  ('pharmacy'),
  ('physiotherapy'),
  ('pediatrics'),
  ('podiatry'),
  ('psychology'),
  ('speech therapy'),
  ('optometry'),
  ('gynecology'),
  ('endocrinology'),
  ('urology'),
  ('neurology')
;

INSERT INTO
  languages (code)
VALUES
  ('aa'),
  ('ab'),
  ('ae'),
  ('af'),
  ('ak'),
  ('am'),
  ('an'),
  ('ar'),
  ('as'),
  ('av'),
  ('ay'),
  ('az'),
  ('ba'),
  ('be'),
  ('bg'),
  ('bi'),
  ('bm'),
  ('bn'),
  ('bo'),
  ('br'),
  ('bs'),
  ('ca'),
  ('ce'),
  ('ch'),
  ('co'),
  ('cr'),
  ('cs'),
  ('cu'),
  ('cv'),
  ('cy'),
  ('da'),
  ('de'),
  ('dv'),
  ('dz'),
  ('ee'),
  ('el'),
  ('en'),
  ('eo'),
  ('es'),
  ('et'),
  ('eu'),
  ('fa'),
  ('ff'),
  ('fi'),
  ('fj'),
  ('fo'),
  ('fr'),
  ('fy'),
  ('ga'),
  ('gd'),
  ('gl'),
  ('gn'),
  ('gu'),
  ('gv'),
  ('ha'),
  ('he'),
  ('hi'),
  ('ho'),
  ('hr'),
  ('ht'),
  ('hu'),
  ('hy'),
  ('hz'),
  ('ia'),
  ('id'),
  ('ie'),
  ('ig'),
  ('ii'),
  ('ik'),
  ('io'),
  ('is'),
  ('it'),
  ('iu'),
  ('ja'),
  ('jv'),
  ('ka'),
  ('kg'),
  ('ki'),
  ('kj'),
  ('kk'),
  ('kl'),
  ('km'),
  ('kn'),
  ('ko'),
  ('kr'),
  ('ks'),
  ('ku'),
  ('kv'),
  ('kw'),
  ('ky'),
  ('la'),
  ('lb'),
  ('lg'),
  ('li'),
  ('ln'),
  ('lo'),
  ('lt'),
  ('lu'),
  ('lv'),
  ('mg'),
  ('mh'),
  ('mi'),
  ('mk'),
  ('ml'),
  ('mn'),
  ('mr'),
  ('ms'),
  ('mt'),
  ('my'),
  ('na'),
  ('nb'),
  ('nd'),
  ('ne'),
  ('ng'),
  ('nl'),
  ('nn'),
  ('no'),
  ('nr'),
  ('nv'),
  ('ny'),
  ('oc'),
  ('oj'),
  ('om'),
  ('or'),
  ('os'),
  ('pa'),
  ('pi'),
  ('pl'),
  ('ps'),
  ('pt'),
  ('qu'),
  ('rm'),
  ('rn'),
  ('ro'),
  ('ru'),
  ('rw'),
  ('sa'),
  ('sc'),
  ('sd'),
  ('se'),
  ('sg'),
  ('si'),
  ('sk'),
  ('sl'),
  ('sm'),
  ('sn'),
  ('so'),
  ('sq'),
  ('sr'),
  ('ss'),
  ('st'),
  ('su'),
  ('sv'),
  ('sw'),
  ('ta'),
  ('te'),
  ('tg'),
  ('th'),
  ('ti'),
  ('tk'),
  ('tl'),
  ('tn'),
  ('to'),
  ('tr'),
  ('ts'),
  ('tt'),
  ('tw'),
  ('ty'),
  ('ug'),
  ('uk'),
  ('ur'),
  ('uz'),
  ('ve'),
  ('vi'),
  ('vo'),
  ('wa'),
  ('wo'),
  ('xh'),
  ('yi'),
  ('yo'),
  ('za'),
  ('zh'),
  ('zu')
;

INSERT INTO
  users (id, email, password_hash, full_name, date_of_birth, gender, email_verified)
VALUES
  ('cuid123456789abcdef0002', 'bob@example.com', '$2b$12$def456fakebcryptpasswordhash1111111111111111111', 'bob johnson', '1975-11-23', 'M', true),
  ('cuid123456789abcdef0003', 'carol@example.com', '$2b$12$ghi789fakebcryptpasswordhash2222222222222222222', 'carol williams', '1990-02-15', 'F', false)
;
INSERT INTO
  experts (id, specialty_id, city, phone)
VALUES
  ('cuid123456789abcdef0002', 1, 'new york', '+1-555-0101'),
  ('cuid123456789abcdef0003', 3, 'san francisco', '+1-555-0303')
;
INSERT INTO
  experts_languages (expert_id, language_id)
VALUES
  ('cuid123456789abcdef0002', 1),
  ('cuid123456789abcdef0002', 2),
  ('cuid123456789abcdef0003', 3)
;
